### PR TITLE
Fix required override keyword for two functions

### PR DESCRIPTION
**Pull request by warpling**
This seems to be a requirement in Swift 5 or Xcode 12?

### CODE REVIEW

**Comment by kmcgill88** [comment]
@warpling thanks for the PR! Could you please update this to the latest Xcode as part of this pr? https://github.com/kmcgill88/McPicker-iOS/blob/master/.travis.yml#L1

**Comment by warpling** [comment]
It’s still in beta so I’m not sure you want that?

**Comment by kmcgill88** [comment]
Pull master and push back to your branch. I updated the travis file.

**Comment by warpling** [comment]
Rebased this so I had to force push but should be good.

**Comment by kmcgill88** [comment]
Addressed and will be available in `3.0.0`

**Pull request closed without merging**
