### PR TITLE
fix bug did selected row

### PR DESCRIPTION
**Pull request by thanhlong12312**
when i push a empty array to data in show method. 
 i scroll in picker, i have a bug in method didselectedrow. 
this bug is index out of range. pickerSelection is empty and component =0 
Please review for me!!

### CODE REVIEW

**Comment by kmcgill88** [comment]
Good find! Thanks for the PR. I will try it out ASAP

**Comment by thanhlong12312** [comment]
okay. Thanks

**Comment by kmcgill88** [comment]
Are you passing some data similar to this and having the problem?

```swift
    let data: [[String]] = [
        ["foo", "bar"],
        [] // <--this causes the index issue?
    ]
```

**Comment by kmcgill88** [comment]
This isn't much different but it feels like it makes a little more sense.

```swift
        if !pickerData[component].isEmpty {
            self.pickerSelection[component] = pickerData[component][row]
            self.selectionChangedHandler?(self.pickerSelection, component)
        }
```

I swapped out `if component < pickerSelection.count {` with ` if !pickerData[component].isEmpty {` because `pickerData` is the source of truth since it's passed in from the public api. It is never mutated. If for some reason a components array is empty then no selection can be made, and we can safely ignore it. If you wouldn't mind swapping that out, I'll merge and publish a patch.

**Comment by thanhlong12312** [comment]
okay men. i like your idea :D

**Comment by thanhlong12312** [comment]
hey man! Merge or fix this bug please !

**Comment by thanhlong12312** [comment]
Thank you so much :D

Vào 07:38, T.3, 9 Th4, 2019 Kevin McGill <notifications@github.com> đã viết:

**Comment by kmcgill88** [comment]
@thanhlong12312 you bet. Thanks for the fix. I will publish `2.0.1` in just a few minutes.

**Comment by thanhlong12312** [comment]
Ok men :D

Vào 07:42, T.3, 9 Th4, 2019 Kevin McGill <notifications@github.com> đã viết:

**Comment by kmcgill88** [comment]
`2.0.1` is live. Thanks again!

**Pull request merged**
