### PR TITLE
Add the possibility to override the UIPickerViewDelegate of the picker.

### PR DESCRIPTION
**Pull request by AlaeddineOuerteni**

### CODE REVIEW

**Comment by kmcgill88** [comment]
Hi @AlaeddineOuerteni I like the idea of flexibility here but I'm not sure adding this is the answer. Have you tried to subclass McPicker and override the delegate methods?

**Comment by AlaeddineOuerteni** [comment]
Hi @kmcgill88,

Yes I tried to do it (although I prefer that the viewVontroller be responsable of that) but there's an error of visibility: "Overriding non-open instance method outside of its defining module"

**Comment by kmcgill88** [comment]
@AlaeddineOuerteni Shoot, yeah I guess that makes sense since the delegate methods are `public` and not `open`. I wouldn't think setting your own delegate would work either though. [Picker data and selections](https://github.com/kmcgill88/McPicker-iOS/blob/master/McPicker/Classes/McPicker.swift#L101-L102) are internal values which are used for the handler closures. Since these are internal you shouldn't have access to them if you used your own delegate. Have you successfully set and used your own picker delegate?

**Comment by AlaeddineOuerteni** [comment]
Yes @kmcgill88,
Right now I'm pointing at my own fork and it works.

**Comment by AlaeddineOuerteni** [comment]
Hello @kmcgill88,

Any news ?

Thanks

**Comment by kmcgill88** [comment]
Hey @AlaeddineOuerteni, sorry I haven't been able to get to this yet. I will try it out soon and get back to you.

**Comment by kmcgill88** [comment]
@AlaeddineOuerteni I tried this last night and although you can set the picker delegate it breaks the `doneHandler`. Per #31 suggestion I created a `SelectionChangedHandler` which was merged in #32. If this delegate approach works for your needs I suggest you continue to use your fork. Thanks!

**Pull request closed without merging**
