### PR TITLE
Added SPM support

### PR DESCRIPTION
**Pull request by lukemmtt**
Did not do any tests to see if this breaks the CocoaPods install.

### CODE REVIEW

**Comment by kmcgill88** [comment]
Hi @lukemmtt  I haven't been actively developing this anymore but i'm happy to add you as a maintainer if you like?

**Comment by lukemmtt** [comment]
That would be great, thanks Kevin! I still use this module to this day in my app TimeFinder, so I'll be glad to help maintain it so long as it remains a part of the project. 
https://apps.apple.com/us/app/schedule-planner-time-finder/id1347447233

**Comment by kmcgill88** [comment]
> Hi @lukemmtt I haven't been actively developing this anymore but i'm happy to add you as a maintainer if you like?

Got you added @lukemmtt !

**Comment by warpling** [comment]
@lukemmtt would love to see this merged if it still works :)

**Comment by lukemmtt** [comment]
@warpling I don't seem to have permission to do that, unfortunately!

@kmcgill88, can you help?

**Comment by kmcgill88** [comment]
@lukemmtt your previous invite to join as a collaborator expired. I just fired off a new invite. Accept that and I think you'll have all the power!

**Comment by lukemmtt** [comment]
Thanks @kmcgill88 ! 🙏🏻

@warpling All taken care of 🚀 Although until we make a new "release", you'd need to ensure to use the master branch rather than the latest official release.

**Comment by warpling** [comment]
Nice work! Maybe worth quickly updating the README and cutting a new tag for anyone else coming along that doesn't see this PR? :)

**Comment by lukemmtt** [comment]
@warpling I'd prefer if you or someone else could attest that this PR hasn't broken anything in the cocoapods version (see my [original comment](https://github.com/kmcgill88/McPicker-iOS/pull/71#issue-1365383762)), then I'd be glad to make a new release

**Pull request merged**
