### PR TITLE
Added Selection change closure

### PR DESCRIPTION
**Pull request by BluePick**
Added Selection change closure to get call back of picker value selection change

### CODE REVIEW

**Comment by kmcgill88** [comment]
I like your approach here. The build is failing and I do have a few suggestions to add.

1. Need test coverage
2. Need to add example code to the README
3. Need to add to the example app
4.  I think it would better if the `selectionChangeHandler` was optional. This would preserve the original signature and people could use this is...optionally. :+1: 
5. Change the signature a little. From `fileprivate var selectionChangeHandler:(_ selectionChange: [Int:String]) -> Void = {_ in }` to maybe `fileprivate var selectionChangeHandler:(_ selections: [Int:String], component: Int, selection: String) -> Void?`. Where `selections` is __all__ selections, `component` is the component that change and `selection` is the value which the component changed to.

I should have time to help out with this in the next day or two. Thanks for submitting a PR. There have been a lot of requests for this feature.

**Comment by kmcgill88** [comment]
@BluePick took your idea and ran with it. It's been merged in a branch I created.

**Comment by BluePick** [comment]
👍

**Comment by BluePick** [comment]
Thanks for refining signature...that's more accurate.

**Pull request closed without merging**
